### ISSUE TITLE
Copyright year typo?

### ISSUE THREAD

**Issue by JeremyGrosser** [joeycastillo/OSO_Arduino_LCD#2]
Is this really Copyright 2012 or is this a typo?

https://github.com/joeycastillo/OSO_Arduino_LCD/blob/3addb19a562b0e176df6f9384e508fc4a5dfcfda/license.txt#L3

**Comment by joeycastillo** [comment]
This is a typo; I started with an Adafruit library before kinda restarting from scratch, and this must have remained. I’ll close this issue when I fix it. Thanks for pointing it out!
